#!/bin/bash
FILENAME=`basename $0`
TMPDIR="tmp"
PSDIR="ps"
MYSQL="/home/boj/infobright/mysql-ib"
COUNT=`$MYSQL --column-names=0 -u root mirrors -e "SELECT COUNT(*) FROM files"`
LENGTH=`$MYSQL --column-names=0 -u root mirrors -e "SELECT SUM(filesize) FROM files"`

$MYSQL --column-names=0 -u root mirrors << EOF > "$TMPDIR/$FILENAME"
SELECT url_0, COUNT(*)/$COUNT, SUM(filesize)/$LENGTH AS c FROM files GROUP BY url_0 ORDER BY c DESC LIMIT 40;
EOF

gnuplot -p << EOF
set title 'Num \& Size of Files in each Distribution (order by FileSize)'
set xlabel ''
set ylabel 'Percentage'
set autoscale
set size 1.5,1.5
set grid noxtics ytics
set key box
set key bottom right
set terminal postscript eps enhanced color
set style data histogram
set style fill solid 0.4 border
set xtics rotate by -45
set bmargin 10
set key top right
set output "$PSDIR/$FILENAME.ps"
plot '$TMPDIR/$FILENAME' using 2:xticlabels(1) title 'Number', '$TMPDIR/$FILENAME' using 3:xticlabels(1) title 'Size'
EOF
