#!/bin/bash
FILENAME=`basename $0`
TMPDIR="tmp"
PSDIR="ps"
MYSQL="/home/boj/infobright/mysql-ib"
bash ./file-traffic-size-acc-log
bash ./file-traffic-size-desc-acc-log
bash ./file-traffic-req-acc-log
bash ./file-traffic-traffic-acc-log

gnuplot -p << EOF
set title 'Cumulative Traffic over Cumulative FileSize'
set xlabel 'Cumulative FileSize order by different metrics (log-scale)'
set ylabel 'Cumulative Traffic'
set autoscale
set logscale x
set size 1.5,1.5
set grid
set key box
set key top left
set terminal postscript eps enhanced color
set output "$PSDIR/$FILENAME.ps"
set style data lines
plot '$TMPDIR/file-traffic-size-acc-log' using 3:4 lw 5 title 'FileSize', \
'$TMPDIR/file-traffic-size-desc-acc-log' using 3:4 lw 5 title 'FileSize DESC', \
'$TMPDIR/file-traffic-req-acc-log' using 3:4 lw 5 title 'Requests Num DESC', \
'$TMPDIR/file-traffic-traffic-acc-log' using 3:4 lw 5 title 'Traffic DESC'
EOF
