#!/bin/bash
FILENAME=`basename $0`
TMPDIR="tmp"
PSDIR="ps"
MYSQL="/home/boj/infobright/mysql-ib"
FILENUM=`$MYSQL --column-names=0 -u root mirrors -e "SELECT COUNT(*) FROM files;"`

$MYSQL --column-names=0 -u root mirrors << EOF | php sample_log.php > "$TMPDIR/$FILENAME"
SELECT filesize, COUNT(*) FROM files GROUP BY filesize ORDER BY filesize;
EOF

gnuplot -p << EOF
set title 'Sorted Filenum by Filesize'
set xlabel 'FileSize (Log-scale)'
set ylabel 'FileNum'
set autoscale
set logscale x
set size 1.5,1.5
set grid
set key box
set key bottom right
set terminal postscript eps enhanced color
set output "$PSDIR/$FILENAME.ps"
set style data lines
set style fill pattern 2
plot '$TMPDIR/$FILENAME' using 1:2 lw 3 notitle with filledcurves y1=0
EOF
