#!/bin/bash
FILENAME=`basename $0`
TMPDIR="tmp"
PSDIR="ps"
MYSQL="/home/boj/infobright/mysql-ib"

$MYSQL --column-names=0 -u root mirrors << EOF | php sample_log_xyacc.php > "$TMPDIR/$FILENAME"
SELECT COUNT(*) * filesize, SUM(traffic) FROM filestat GROUP BY filesize ORDER BY filesize;
EOF

gnuplot -p << EOF
set title 'Cumulative Traffic over Cumulative FileSize'
set xlabel 'Cumulative FileSize (order by FileSize)'
set ylabel 'Cumulative Traffic'
set autoscale
set size 1.5,1.5
set grid
set key box
set key bottom right
set terminal postscript eps enhanced color
set output "$PSDIR/$FILENAME.ps"
set style data lines
set style fill pattern 2
plot '$TMPDIR/$FILENAME' using 3:4 lw 3 notitle with filledcurves y1=0
EOF
