#!/bin/bash
FILENAME=`basename $0`
TMPDIR="tmp"
PSDIR="ps"
MYSQL="/home/boj/infobright/mysql-ib"
FILENUM=`$MYSQL --column-names=0 -u root mirrors -e "SELECT COUNT(*) FROM files;"`

$MYSQL --column-names=0 -u root mirrors << EOF | php sample_revlog_xyacc.php > "$TMPDIR/$FILENAME"
SELECT COUNT(*), COUNT(*) * filesize FROM files GROUP BY filesize ORDER BY filesize;
EOF

gnuplot -p << EOF
set title 'Accumulated FileSize by FileNum sorted by Size (log scale y)'
set xlabel 'FileNum'
set ylabel 'FileSize'
set autoscale
set logscale y
set size 1.5,1.5
set grid
set key box
set key bottom right
set terminal postscript eps enhanced color
set output "$PSDIR/$FILENAME.ps"
set style data lines
set style fill pattern 2
plot '$TMPDIR/$FILENAME' using 3:4 lw 3 notitle with filledcurves y1=0
EOF
