#!/bin/bash
FILENAME=`basename $0`
TMPDIR="tmp"
PSDIR="ps"
MYSQL="/home/boj/infobright/mysql-ib"

# the first and last day has not enough data
$MYSQL --column-names=0 -u root mirrors << EOF > "$TMPDIR/$FILENAME"
SELECT yearday, COUNT(*), SUM(length) FROM log WHERE yearday>142 AND yearday<193 GROUP BY yearday ORDER BY yearday;
EOF

gnuplot -p << EOF
set title 'Requests \& Traffic in 50 days'
set xlabel 'Time of the day'
set ylabel 'Requests'
set ytics nomirror
set y2tics
set y2label 'Traffic (Bytes)'
set yrange [0:1.2e7]
set y2range [0:1.3e12]
set xdata time
set timefmt "%j"
set format x "%m-%d"
set size 1.5,1.5
set pointsize 1
set grid
set key box
set key bottom right
set terminal postscript eps enhanced color
set output "$PSDIR/$FILENAME.ps"
set style data linespoints
set linestyle 1 linetype 1 lw 3 lc rgb "red"
set linestyle 2 linetype 1 lw 3 lc rgb "blue"
plot '$TMPDIR/$FILENAME' using 1:2 linestyle 1 pointtype 6 title 'Request count' axes x1y1, '$TMPDIR/$FILENAME' using 1:3 linestyle 2 pointtype 8 title 'Traffic' axes x1y2
EOF
