#!/bin/bash
FILENAME=`basename $0`
TMPDIR="tmp"
PSDIR="ps"
MYSQL="/home/boj/infobright/mysql-ib"

$MYSQL --column-names=0 -u root mirrors << EOF | php sample_log_xyacc.php > "$TMPDIR/$FILENAME"
SELECT COUNT(*), length FROM log GROUP BY length ORDER BY length;
EOF

gnuplot -p << EOF
set title 'Request Num sorted by Request Length'
set xlabel 'Request Num'
set ylabel 'Request Length (Log-scale)'
set autoscale
set logscale y
set size 1.5,1.5
set grid
set key box
set key bottom right
set terminal postscript eps enhanced color
set output "$PSDIR/$FILENAME.ps"
set style data lines
set style fill pattern 2
plot '$TMPDIR/$FILENAME' using 3:2 lw 3 notitle with filledcurves y1=0
EOF
