#!/bin/bash
FILENAME=`basename $0`
TMPDIR="tmp"
PSDIR="ps"
MYSQL="/home/boj/infobright/mysql-ib"

$MYSQL --column-names=0 -u root mirrors << EOF | php sample_revlog_acc.php > "$TMPDIR/$FILENAME"
SELECT length, length * COUNT(*) FROM log GROUP BY length ORDER BY length;
EOF

gnuplot -p << EOF
set title 'Cumulative Request Traffic sorted by Request Length'
set xlabel 'Request Length (log-scale)'
set ylabel 'Cumulative Traffic'
set autoscale
set logscale x
set size 1.5,1.5
set grid
set key box
set key bottom right
set terminal postscript eps enhanced color
set output "$PSDIR/$FILENAME.ps"
set style data lines
set style fill pattern 2
plot '$TMPDIR/$FILENAME' using 1:3 lw 3 notitle with filledcurves y1=0
EOF
