#!/bin/bash
FILENAME=`basename $0`
TMPDIR="tmp"
PSDIR="ps"
MYSQL="/home/boj/infobright/mysql-ib"
COUNT=`$MYSQL --column-names=0 -u root mirrors -e "SELECT COUNT(*) FROM log"`
LENGTH=`$MYSQL --column-names=0 -u root mirrors -e "SELECT SUM(length) FROM log"`

$MYSQL --column-names=0 -u root mirrors << EOF > "$TMPDIR/$FILENAME"
SELECT status, COUNT(*)/$COUNT, SUM(length)/$LENGTH AS c FROM log GROUP BY status ORDER BY status;
EOF

gnuplot -p << EOF
set title 'Request \& Traffic among HTTP status codes'
set xlabel 'HTTP Status Code'
set ylabel 'Percentage'
set autoscale
set size 1.5,1.5
set grid noxtics ytics
set key box
set key bottom right
set terminal postscript eps enhanced color
set style data histogram
set style fill solid 0.4 border
set output "$PSDIR/$FILENAME.ps"
plot '$TMPDIR/$FILENAME' using 2:xticlabels(1) title 'Requests', '$TMPDIR/$FILENAME' using 3:xticlabels(1) title 'Traffic'
EOF
