#!/bin/bash
FILENAME=`basename $0`
TMPDIR="tmp"
PSDIR="ps"
MYSQL="/home/boj/infobright/mysql-ib"
MYSQLCMD="$MYSQL --column-names=0 -u root mirrors"

COUNT=`$MYSQLCMD -e 'SELECT COUNT(*) FROM sess;'`
REQUESTS=`$MYSQLCMD -e 'SELECT SUM(requests) FROM sess;'`
DURATION=`$MYSQLCMD -e 'SELECT SUM(duration) FROM sess;'`
TRAFFIC=`$MYSQLCMD -e 'SELECT SUM(traffic) FROM sess;'`

$MYSQLCMD << EOF | php sample_log_allacc.php > "$TMPDIR/$FILENAME"
SELECT 1, requests, duration, traffic FROM sess ORDER BY duration DESC LIMIT 10000;
EOF

gnuplot -p << EOF
set title 'Cumulative Ratio of Requests, Duration and Traffic over Sessions'
set xlabel 'Sessions order by Duration DESC'
set ylabel 'Cumulative Ratio of Total'
set autoscale
set size 1.5,1.5
set grid
set key box
set key top right
set terminal postscript eps enhanced color
set output "$PSDIR/$FILENAME.ps"
set style data lines
plot '$TMPDIR/$FILENAME' using 1:(\$2/$REQUESTS) lw 5 title 'Request count', \
'$TMPDIR/$FILENAME' using 1:(\$3/$DURATION) lw 5 title 'Duration', \
'$TMPDIR/$FILENAME' using 1:(\$4/$TRAFFIC) lw 5 title 'Traffic'
EOF
