#!/bin/bash
FILENAME=`basename $0`
TMPDIR="tmp"
PSDIR="ps"
MYSQL="/home/boj/infobright/mysql-ib"
MYSQLCMD="$MYSQL --column-names=0 -u root mirrors"

COUNT=`$MYSQLCMD -e 'SELECT COUNT(*) FROM sess;'`
REQUESTS=`$MYSQLCMD -e 'SELECT SUM(requests) FROM sess;'`
DURATION=`$MYSQLCMD -e 'SELECT SUM(duration) FROM sess;'`
TRAFFIC=`$MYSQLCMD -e 'SELECT SUM(traffic) FROM sess;'`

$MYSQLCMD << EOF > "$TMPDIR/$FILENAME"
SELECT CONCAT(FLOOR(daymin/60), ':', MOD(daymin,60)), c*100/$COUNT, r*100/$REQUESTS, d*100/$DURATION, t*100/$TRAFFIC FROM (SELECT daymin, COUNT(*) AS c, SUM(requests) AS r, SUM(duration) AS d, SUM(traffic) AS t FROM (SELECT FLOOR(MOD(start_time,86400)/60) AS daymin, requests, duration, traffic FROM sess) AS x GROUP BY daymin ORDER BY daymin) AS y;
EOF

gnuplot -p << EOF
set title 'Session statistics at different Time in a day'
set xlabel 'Time in a day'
set ylabel 'Ratio of total'
set xdata time
set timefmt "%H:%M"
set format x "%H:%M"
set autoscale
set yrange [0 to 0.0017]
set size 1.5,1.5
set grid
set key box
set key top right
set terminal postscript eps enhanced color
set output "$PSDIR/$FILENAME.ps"
set style data lines
plot '$TMPDIR/$FILENAME' using 1:(\$2/100) smooth bezier lw 5 title 'Session count (Bezier smoothed)', \
'$TMPDIR/$FILENAME' using 1:(\$3/100) smooth bezier lw 5 title 'Request count (Bezier smoothed)', \
'$TMPDIR/$FILENAME' using 1:(\$4/100) smooth bezier lw 5 title 'Duration (Bezier smoothed)', \
'$TMPDIR/$FILENAME' using 1:(\$5/100) smooth bezier lw 5 title 'Traffic (Bezier smoothed)'
EOF
